org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# 指定 Gradle 使用的 JDK（本机系统 PATH 只有 JRE 1.8，此处指向 HMCL 内置的 JDK 17.0.15）
org.gradle.java.home=C:/Users/HP/AppData/Roaming/.hmcl/java/windows-x86_64/mojang-java-runtime-beta
